server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://database-1.c6jqkanlheep.ap-northeast-2.rds.amazonaws.com/CGV?autoReconnect=true # 변경해주세요
    username: admin # 변경해주세요
    password: qud9578957 # 변경해주세요
    driver-class-name: com.mysql.cj.jdbc.Driver